# Generated by Django 4.2.7 on 2023-11-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
