# Generated by Django 4.2.7 on 2023-11-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestiaApp', '0002_alter_bestia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestia',
            name='cultura',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='bestia',
            name='descripcion',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='bestia',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
